{ config, lib, pkgs, ... }: 

{
  imports =[ 
    ./hardware-configuration.nix                            # Include hardware config (generated by NixOS)
    ../../system/common/common.nix                          # Include common settings/services/programs
  ];

  # DO NOT CHANGE
  system.stateVersion = "25.05";

  # Boot settings
  boot = {

    # Kernel module for CD driver
    kernelModules = [ "sg" ];
    
    # Bootloader settings
    loader = { 
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    
    # ZFS settings
    supportedFilesystems = [ "zfs" ];
    zfs.extraPools = [ "rpool" ];
    # rollback root to blank snapshot (note the lib.mkAfter means this command appends, not replaces others)
    initrd.postDeviceCommands = lib.mkAfter ''
      zpool import -N rpool
      zfs rollback -r rpool/root@blank
    '';
  };

  # Networking
  networking = {
    hostName = "ripper";
    hostId = "ba087eb7";
    networkmanager.enable = true;
  };

    # Bind-mount persistant directories
  fileSystems."/etc/NetworkManager/system-connections" = {
    device = "/persist/etc/NetworkManager/system-connections";
    options = [ "bind" ];
  };

  # Tailscale state
  fileSystems."/var/lib/tailscale" = {
    device = "/persist/var/lib/tailscale";
    options = [ "bind" ];
  };

  # jack user SSH keys
  fileSystems."/home/jack/.ssh" = {
    device = "/persist/home/jack/.ssh";
    options = [ "bind" ];
  };

  # nixos-config
  fileSystems."/home/jack/nixos-config" = {
    device = "/persist/home/jack/nixos-config";
    options = [ "bind" ];
  };

  # Set directory/file permissions and create symlinks
  systemd.tmpfiles.rules = [
    # Permissions for bind mounted directories (also creates directories if they don't exist)
    "d /persist/etc/NetworkManager/system-connections 0700 root root - -" # NetworkManager connections
    "d /persist/var/lib/tailscale 0700 root root - -" # Tailscale state
    "d /persist/home/jack/.ssh 0700 jack users - -" # Jack user SSH keys
    "d /persist/home/jack/nixos-config 0755 jack users - -" # nixos-config
    
    # Permissions for symlinked files (also creates file and parent directories if they don't exist)
    "f /persist/home/jack/.gitconfig 0644 jack users - -" # Git configuration

    # Symlink persistent files
    "L+ /home/jack/.gitconfig - - - - /persist/home/jack/.gitconfig" # Symlink .gitconfig
  ];

  # Graphical settings
  services.xserver = {
    videoDrivers = [ "nvidia" ]; # Graphics drivers
    desktopManager.pantheon.enable = true; # Use Pantheon desktop environment
    displayManager.lightdm = {
      enable = true; # Use LightDM as display manager
      greeters.pantheon.enable = true; # Use Pantheon greeter
    };
  };
  hardware = {
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libglvnd
        vulkan-loader
      ];
    };
    nvidia = {
      modesetting.enable = true;
      powerManagement.enable = false;
      powerManagement.finegrained = false;
      open = false;
      nvidiaSettings = true;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };
  };

  # Bluetooth settings
  services.blueman.enable = false; # Enable blueman
  
  # Host specific system packages
  environment.systemPackages = with pkgs; [
    makemkv
    handbrake
    brave
    kitty
    ghostty
    mpv
    virt-manager
  ];

  users.users.jack = {
    isNormalUser = true;
    hashedPassword = "$y$j9T$PtbhYydbhh.z0qInjgrQS1$0oLkk3FlJztVtmVJqpWQWCDs8kdX2zzMkJKQkkzAtu9";
    shell = pkgs.zsh;
    description = "Jack";
    extraGroups = [ 
      "wheel" 
      "networkmanager" 
      "libvirtd" 
      "kvm" 
    ];
  };

  users.users.root.hashedPassword = "$y$j9T$PtbhYydbhh.z0qInjgrQS1$0oLkk3FlJztVtmVJqpWQWCDs8kdX2zzMkJKQkkzAtu9";

}
