{ config, lib, pkgs, ... }: 

{
  imports =[ 
    ./hardware-configuration.nix                            # Include hardware config (generated by NixOS)
    ./desktop-environment.nix                               # Include desktop environments
    ./users.nix                                             # Include users
    ../../system/common/common.nix                          # Include common settings/services/programs
  ];

  # DO NOT CHANGE
  system.stateVersion = "25.05";

  # Set desktop environment
  desktopEnv = "xmonad";

  # Home manager
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "backup";
  };

  # Boot settings
  boot = {
    loader = { 
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    supportedFilesystems = [ "zfs" ];
    zfs.forceImportRoot = true;
    # rollback root to blank snapshot
    initrd.postDeviceCommands = lib.mkAfter ''
      zpool import -Nf zpool
      zfs rollback -r zpool/local/root@blank
    '';
  };

  # Symlink etc files after recreating root
  systemd.tmpfiles.rules = [
    "d /persist/etc/NetworkManager/system-connections 0700 root root - -"
    "L+ /etc/NetworkManager/system-connections - - - - /persist/etc/NetworkManager/system-connections"
  ];

  # Networking
  networking = {
    hostName = "watson";
    hostId = "36306665";
    networkmanager.enable = true;
  };

  # Bluetooth settings
  services.blueman.enable = true; # Enable blueman
  hardware.bluetooth = {
    enable = true;                # Enable Bluetooth
    powerOnBoot = false;          # Don't turn bluetooth on at boot
  };

  # Host specific system packages
  environment.systemPackages = with pkgs; [
    kitty #just in case home-manager shits the bed
  ];

  users.users.root.hashedPassword = "$y$j9T$PtbhYydbhh.z0qInjgrQS1$0oLkk3FlJztVtmVJqpWQWCDs8kdX2zzMkJKQkkzAtu9";

}
